In [3]:
from pathlib import Path
import os

# Change to parent directory
os.chdir(Path.cwd().parent)

In [4]:
#check if the notebook is in the same level as the root of project
%pwd

'/home/vutuan/Documents/MDC_LInh/New_experiment'

In [5]:
from analysis import current_work
import numpy as np

In [6]:
#This cell is for futher analysis if needed
data_mdc = 'WQanimals'
runner_mdc= current_work.MDC(data_mdc)
runner_mdc.prediction_each_fold(current_work.MDC.bsc_cautious, runner_mdc.probas[0],2)[3]

[array([1], dtype=object),
 array([2, 1], dtype=object),
 array([1], dtype=object),
 array([1], dtype=object),
 array([1], dtype=object),
 array([1], dtype=object),
 array([1, 2], dtype=object)]

In [7]:
runner_mdc.y[runner_mdc.fold_indices[0]][0]

array([2, 1, 1, 2, 1, 1, 1])

In [23]:
data_mlc = 'emotions'
runner_mlc_local= current_work.MLC(data_mlc ,'local')
#None in the first parameter because for local MLC, no need to specify the prediction type,it will use bsc_cautious (cautious = abstention)
runner_mlc_local.prediction_each_fold(None, runner_mlc_local.probas[0],2.4)[2]

[array([0], dtype=object),
 array([0, 1], dtype=object),
 array([1, 0], dtype=object),
 array([0], dtype=object),
 array([0, 1], dtype=object),
 array([0, 1], dtype=object)]

In [28]:
runner_mlc_global= current_work.MLC(data_mlc ,'global')

runner_mlc_global.global_MLC_predictions(runner_mlc_global.probas[2],3)[1]

[array([1]), array([0]), array([0]), array([0]), array([0]), array([0, 1])]

In [15]:
data_mcc = 'yeast'
runner_yeast = current_work.MCC(data_mcc)
pred_MCC= runner_yeast.prediction_each_fold(current_work.MCC.bsc_cautious, runner_yeast.probas[0],2.2)[0]

In [8]:
pred_MCC

array([0, 7], dtype=object)

In [41]:
runner_yeast.y[runner_yeast.fold_indices[0]][0]

np.int64(0)

In [61]:
def combine(truth, pred):
    if isinstance(pred,list):
        for x, y in zip(truth, pred):
            print(x, y, end=' ')
            if x in y:
                print('here')
            else:
                print()
    else:
        return None


        
    
  


pred = runner_mlc.prediction_each_fold(None, runner_mlc.probas[0],2.2)[0]
truth = runner_mlc.y[runner_mlc.fold_indices[0]][0]
for x, y in zip(truth, pred):
    print(x, y, end=' ')
    if x in y:
        print('here = and ', len(y))
    else:
        print()



0 [0 1] here = and  2
1 [0] 
0 [0 1] here = and  2
0 [0] here = and  1
0 [0 1] here = and  2
1 [0 1] here = and  2


In [65]:
runner_mlc.prediction_each_fold(None, runner_mlc.probas[0],2.2)[0]

[array([0, 1], dtype=object),
 array([0], dtype=object),
 array([0, 1], dtype=object),
 array([0], dtype=object),
 array([0, 1], dtype=object),
 array([0, 1], dtype=object)]

In [63]:
len(pred)

6

In [59]:
pred = runner_yeast.prediction_each_fold(current_work.MCC.bsc_cautious, runner_yeast.probas[0],2.2)[0]
truth = runner_yeast.y[runner_yeast.fold_indices[0]][0]
zipped = zip([truth], [pred])
for x, y in zipped:
    print(x, y, end=' ')
    if x in y:
        print('here')
    else:
        print()

0 [0 7] here


In [60]:
len(zipped)

TypeError: object of type 'zip' has no len()